### ISSUE TITLE
ERROR    'copyText'

### ISSUE THREAD

**Issue by tiangangzhou** [TKkk-iOSer/wechat-alfred-workflow#20]
安装的WeChat Plugin版本为release 2.0，但是Alfred显示的是1.0.0
Mac OS X 10.11.6
WeChat Assistant 1.7.1
Alfred v3.5.1

![image](https://user-images.githubusercontent.com/24786426/44537688-0510f180-a732-11e8-8e20-8c9c6b675069.png)

```
Starting debug for 'WeChat Plugin'

[2018-08-24 00:04:51][ERROR: input.scriptfilter] Code 1: .
00:04:51 workflow.py:2055 DEBUG    ---------- WeChat Plugin (1.0.0) ----------
00:04:51 workflow.py:2074 ERROR    'copyText'
Traceback (most recent call last):
  File "/Users/zhoutiangang/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.423CDC7F-9F14-40DA-BB72-A6FE7C6B05E7/workflow/workflow.py", line 2067, in run
    func(self)
  File "search.py", line 23, in main
    copyText = item['copyText']
KeyError: 'copyText'
00:04:51 workflow.py:2097 DEBUG    ---------- finished in 0.020s ----------
```

**Comment by tiangangzhou** [comment]
#18 发现这个issue也提到了，wechat-alfred-workflow上次commit是12天前，现在用`git clone`的方式更新了仍然不能使用。

**Comment by qbosen** [comment]
@VincentZhou98  和`alfred workflow` 没关系， 是小助手没更新。`git cloone` 微信小助手整个项目，使用项目里面的`Other/install.sh`进行安装。

**Comment by tiangangzhou** [comment]
现在仍然有闪退问题，`wx+空格+一些字符` 之后会闪退

Alfred显示正常
```
[2018-08-24 10:53:10][STDERR: input.scriptfilter] .
10:53:10 workflow.py:2055 DEBUG    ---------- WeChat Plugin (1.0.0) ----------
10:53:10 workflow.py:1462 DEBUG    reading settings from /Users/zhoutiangang/Library/Application Support/Alfred 3/Workflow Data/tkkk.wechatPlugin/settings.json
10:53:10 workflow.py:2248 DEBUG    set last run version: 1.0.0
10:53:10 workflow.py:2097 DEBUG    ---------- finished in 0.047s ----------
```

Apple crash log 如下
[Apple crash log](https://pastebin.com/8N4AFEPi)

WeChatPlugin && WeChat workflow && WeChat版本已经更新到最新

**Comment by UnleashHell** [comment]
有同样问题 alfred输入wx搜索联系人时会崩溃，求修复。。

**Comment by TKkk-iOSer** [comment]
@UnleashHell @VincentZhou98 先把微信小助手更新下再说。

```
cd ~/Downloads && rm -rf WeChatPlugin-MacOS && git clone https://github.com/TKkk-iOSer/WeChatPlugin-MacOS.git --depth=1 && ./WeChatPlugin-MacOS/Other/Install.sh
```

**Comment by UnleashHell** [comment]
@TKkk-iOSer 小助手是最新的还是会闪退
系统：10.13.6
alfred版本：3.6.2
小助手版本：1.7.1（关于小助手那里显示的）

**Comment by TKkk-iOSer** [comment]
@UnleashHell 上面的 shell 执行过了么。没执行的话执行下。我更新代码没更新版本，小调整而已。

**Comment by UnleashHell** [comment]
http://owicp4z3x.bkt.clouddn.com/20180829144831_58Vw2g_Screenshot.jpeg
@TKkk-iOSer 是执行了的

**Comment by UnleashHell** [comment]
找了个低版本的微信可用

**Comment by TKkk-iOSer** [comment]
Fixed
