### ISSUE TITLE
搜索报错

### ISSUE THREAD

**Issue by KilluaaaCHEN** [TKkk-iOSer/wechat-alfred-workflow#23]
### Alfred版本3.4.1
报错日志:
```zsh
Starting debug for 'WeChat Plugin'

[2018-08-31 11:10:06][STDERR: input.scriptfilter] .
11:10:06 workflow.py:2055 DEBUG    ---------- WeChat Plugin (2.0.0) ----------
11:10:06 workflow.py:1462 DEBUG    reading settings from /Users/killua/Library/Application Support/Alfred 3/Workflow Data/tkkk.wechatPlugin/settings.json
11:10:06 workflow.py:2248 DEBUG    set last run version: 2.0.0
11:10:06 workflow.py:2097 DEBUG    ---------- finished in 0.021s ----------
[2018-08-31 11:10:09][ERROR: input.scriptfilter] Code 1: .
11:10:09 workflow.py:2055 DEBUG    ---------- WeChat Plugin (2.0.0) ----------
11:10:09 workflow.py:2074 ERROR    ''
Traceback (most recent call last):
  File "/Users/killua/Documents/微云/Mac_Software/Alfred.alfredpreferences/workflows/user.workflow.59560B1D-C5AB-4CDB-8A0C-4307EFFB1A88/workflow/workflow.py", line 2067, in run
    func(self)
  File "search.py", line 13, in main
    result = web.get(url=url)
  File "/Users/killua/Documents/微云/Mac_Software/Alfred.alfredpreferences/workflows/user.workflow.59560B1D-C5AB-4CDB-8A0C-4307EFFB1A88/workflow/web.py", line 583, in get
    stream=stream)
  File "/Users/killua/Documents/微云/Mac_Software/Alfred.alfredpreferences/workflows/user.workflow.59560B1D-C5AB-4CDB-8A0C-4307EFFB1A88/workflow/web.py", line 571, in request
    return Response(req, stream)
  File "/Users/killua/Documents/微云/Mac_Software/Alfred.alfredpreferences/workflows/user.workflow.59560B1D-C5AB-4CDB-8A0C-4307EFFB1A88/workflow/web.py", line 214, in __init__
    self.raw = urllib2.urlopen(request)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
11:10:09 workflow.py:2097 DEBUG    ---------- finished in 0.312s ----------
[2018-08-31 11:12:03][STDERR: input.scriptfilter] .
11:12:03 workflow.py:2055 DEBUG    ---------- WeChat Plugin (2.0.0) ----------
11:12:03 workflow.py:1462 DEBUG    reading settings from /Users/killua/Library/Application Support/Alfred 3/Workflow Data/tkkk.wechatPlugin/settings.json
11:12:03 workflow.py:2248 DEBUG    set last run version: 2.0.0
11:12:03 workflow.py:2097 DEBUG    ---------- finished in 0.010s ----------
```

**Comment by TKkk-iOSer** [comment]
Fixed
