### ISSUE TITLE
微信 2.3.18 闪退

### ISSUE THREAD

**Issue by magicento** [TKkk-iOSer/wechat-alfred-workflow#24]

**Comment by Fanchao-Qi** [comment]
+1
在Alfred命令框中输入wx 之后再输入任意字符之后微信就会闪退。

- MAC系统版本：10.13.6 (17G65)
- 微信版本：2.3.18 (11431)
- Alfred 版本：3.6.2 [922]
- workflow版本：2.0

Alfred错误记录：
```
[2018-09-06 19:12:55][STDERR: input.scriptfilter] .
19:12:54 workflow.py:2055 DEBUG    ---------- WeChat Plugin (2.1.0) ----------
19:12:55 workflow.py:1462 DEBUG    reading settings from /Users/qfc/Library/Application Support/Alfred 3/Workflow Data/tkkk.wechatPlugin/settings.json
19:12:55 workflow.py:2248 DEBUG    set last run version: 2.1.0
19:12:55 workflow.py:2097 DEBUG    ---------- finished in 0.197s ----------
[2018-09-06 19:12:58][ERROR: input.scriptfilter] Code 1: .
19:12:58 workflow.py:2055 DEBUG    ---------- WeChat Plugin (2.1.0) ----------
19:12:58 workflow.py:2074 ERROR    ''
Traceback (most recent call last):
  File "/Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.4E25F705-D5A1-4D2F-B236-9339DE558811/workflow/workflow.py", line 2067, in run
    func(self)
  File "search.py", line 13, in main
    result = web.get(url=url)
  File "/Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.4E25F705-D5A1-4D2F-B236-9339DE558811/workflow/web.py", line 583, in get
    stream=stream)
  File "/Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.4E25F705-D5A1-4D2F-B236-9339DE558811/workflow/web.py", line 571, in request
    return Response(req, stream)
  File "/Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.4E25F705-D5A1-4D2F-B236-9339DE558811/workflow/web.py", line 214, in __init__
    self.raw = urllib2.urlopen(request)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
19:12:58 workflow.py:2097 DEBUG    ---------- finished in 0.386s ----------
```

**Comment by chentao7v** [comment]
同，不能搜索好友了

**Comment by TKkk-iOSer** [comment]
Fixed
