### ISSUE TITLE
3.0还是不能用

### ISSUE THREAD

**Issue by xyiili** [TKkk-iOSer/wechat-alfred-workflow#59]
3.0还是不能用，电脑是：m1pro

**Comment by TKkk-iOSer** [comment]
安装
下载 WeChat Plugin.alfredworkflow
安装requests：pip install requests
打开微信-菜单栏-微信小助手-小助手-开启alfred功能

**Comment by xyiili** [comment]
这三步都做了，还是不行，输入wx后闪一下，然后再输内容不响应。

**Comment by xyiili** [comment]
> 安装
> 下载 WeChat Plugin.alfredworkflow
> 安装requests：pip install requests
> 打开微信-菜单栏-微信小助手-小助手-开启alfred功能

这三步都做了，还是不行，输入wx后闪一下，然后再输内容不响应。

**Comment by xiangdao0309** [comment]
一样，安装了3.0也是不行，三步也都做了

**Comment by TKkk-iOSer** [comment]
打开 Alfred - Debug 看看提示。另外这个需要 Alfred version >= 4
<img width="400" alt="image" src="https://user-images.githubusercontent.com/11961989/226242501-28b6a2c4-b8c7-454f-bd90-4e84efa8e66a.png">

**Comment by xiangdao0309** [comment]
> 打开 Alfred - Debug 看看提示。另外这个需要 Alfred version >= 4 <img alt="image" width="400" src="https://user-images.githubusercontent.com/11961989/226242501-28b6a2c4-b8c7-454f-bd90-4e84efa8e66a.png">

<img width="1280" alt="CleanShot 2023-03-20 at 14 01 39@2x" src="https://user-images.githubusercontent.com/26345162/226259570-8c2c6360-cfd6-4cf2-a9e4-c4aa734ba53a.png">

**Comment by xiangdao0309** [comment]
显示没有requests模块，但其实是已安装的

**Comment by xyiili** [comment]
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/72333592/226263555-e4b32e68-7373-4bcb-8156-ad5b9b5f4fa6.png">

**Comment by xiangdao0309** [comment]
> 谢谢大佬，加上绝对路径OK了

**Comment by xyiili** [comment]
> 谢谢大佬，加上绝对路径OK了

怎么搞？

**Comment by xyiili** [comment]
> 谢谢大佬，加上绝对路径OK了

我也搞定了，确实换成绝对路径就好了。

**Comment by beijiahiddink** [comment]
出这个问题应该是机器上有两套python3的环境，脚本默认走的是/usr/bin/python3，执行的pip安装的对应的环境有可能是/usr/local/bin/python3，改一下alfred里面流程把python3换成你实际想要的环境就行

**Comment by AronX** [comment]
3.0 显示“请先启动微信”，小助手已开启。大佬看下


[15:21:20.264] WeChat Plugin[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.18F4088B-2203-4F6B-B0DA-F901826E48EA%3E7DECB235-5455-435D-90AF-1A51C26046DD)] Queuing argument '(null)'
[15:21:20.413] WeChat Plugin[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.18F4088B-2203-4F6B-B0DA-F901826E48EA%3E7DECB235-5455-435D-90AF-1A51C26046DD)] Script with argv '(null)' finished
[15:21:20.417] STDERR: WeChat Plugin[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.18F4088B-2203-4F6B-B0DA-F901826E48EA%3E7DECB235-5455-435D-90AF-1A51C26046DD)] .
15:21:20 workflow.py:2093 DEBUG    ---------- WeChat Plugin (3.0.0) ----------
15:21:20 connectionpool.py:228 DEBUG    Starting new HTTP connection (1): 127.0.0.1:52700
15:21:20 workflow.py:1483 DEBUG    reading settings from /Users/chengzixu/Library/Application Support/Alfred/Workflow Data/tkkk.wechatPlugin/settings.json
15:21:20 workflow.py:2314 DEBUG    set last run version: 3.0.0
15:21:20 workflow.py:2136 DEBUG    ---------- finished in 0.005s ----------
[15:21:20.418] WeChat Plugin[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.18F4088B-2203-4F6B-B0DA-F901826E48EA%3E7DECB235-5455-435D-90AF-1A51C26046DD)] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>请先启动微信 &amp; 登录…</title><subtitle>并确保安装微信小助手</subtitle></item></items

**Comment by kimizhangzm** [comment]
[12:38:09.863] WeChat Plugin[Script Filter] Processing complete
[12:38:09.864] WeChat Plugin[Script Filter] Passing output '0' to Run Script
[12:38:09.895] ERROR: WeChat Plugin[Run Script] Traceback (most recent call last):
  File "sendMsg.py", line 3, in <module>
    from workflow import Workflow
  File "/Users/kimizhangzm/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.EFE4AE89-DDAC-4F49-BE8D-4B74A591FF64/workflow/__init__.py", line 19, in <module>
    from .workflow import (
  File "/Users/kimizhangzm/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.EFE4AE89-DDAC-4F49-BE8D-4B74A591FF64/workflow/workflow.py", line 585
    is_binary: Optional[bool] = None
             ^
SyntaxError: invalid syntax

**Comment by oscar-meng-gmail** [comment]
我也出现了同样的问题。
<title>请先启动微信 & 登录…</title>并确保安装微信小助手</items
请问大佬解决了吗？（微信已经打开。小助手的开启alfred也已经打开）

**Comment by lsczy** [comment]
## 一开始报openssl版本问题，我更新了1.1的，现在这个报错啥端口没开通吧？我都☑️了
<img width="308" alt="image" src="https://github.com/TKkk-iOSer/wechat-alfred-workflow/assets/34963803/b34ca964-5245-47f9-a41c-8ee524caaaf8">

### 报错信息
[16:44:28.553] WeChat Plugin[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.09560B9B-651F-44E8-8416-0F1706C56125%3E7DECB235-5455-435D-90AF-1A51C26046DD)] Queuing argument '(null)'
[16:44:28.661] WeChat Plugin[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.09560B9B-651F-44E8-8416-0F1706C56125%3E7DECB235-5455-435D-90AF-1A51C26046DD)] Script with argv '(null)' finished
[16:44:28.667] STDERR: WeChat Plugin[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.09560B9B-651F-44E8-8416-0F1706C56125%3E7DECB235-5455-435D-90AF-1A51C26046DD)] .
16:44:28 workflow.py:2093 DEBUG    ---------- WeChat Plugin (3.0.0) ----------
16:44:28 connectionpool.py:204 DEBUG    Starting new HTTP connection (1): 127.0.0.1:57270
16:44:28 workflow.py:1483 DEBUG    reading settings from /Users/xxx/Library/Application Support/Alfred/Workflow Data/tkkk.wechatPlugin/settings.json
16:44:28 workflow.py:2314 DEBUG    set last run version: 3.0.0
16:44:28 workflow.py:2136 DEBUG    ---------- finished in 0.005s ----------
[16:44:28.668] WeChat Plugin[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.09560B9B-651F-44E8-8416-0F1706C56125%3E7DECB235-5455-435D-90AF-1A51C26046DD)] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>请先启动微信 &amp; 登录…</title><subtitle>并确保安装微信小助手</subtitle></item></items>

**Comment by friday-ckp** [comment]
![image](https://github.com/TKkk-iOSer/wechat-alfred-workflow/assets/59718538/e270fe42-1714-45ba-b887-409fe2add32f)
